apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    application: catalogue-db
  name: catalogue-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        application: catalogue-db
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: socksdb
        - name: MYSQL_ROOT_PASSWORD
        image: weaveworksdemos/catalogue-db:0.3.0
        name: catalogue-db
        ports:
        - containerPort: 3306
        resources: {}
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 10
      hostname: catalogue-db
      restartPolicy: Always
status: {}
