apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: catalogue-db
  name: catalogue-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    application: catalogue-db
status:
  loadBalancer: {}
