apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: front-end
  name: front-end
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 8079
  selector:
    application: front-end
status:
  loadBalancer: {}
